credentials:
  users:
    admin:
      password: 'topsecret'
      roles: [ super ]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
              - uri: '127.0.0.1:3302'
