credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]

replication:
  peers:
    - replicator:topsecret@127.0.0.1:3301
    - replicator:topsecret@127.0.0.1:3302
    - replicator:topsecret@127.0.0.1:3303
  failover: election

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
          instance002:
            iproto:
              listen:
              - uri: '127.0.0.1:3302'
          instance003:
            iproto:
              listen:
              - uri: '127.0.0.1:3303'