credentials:
  users:
    dbadmin:
      password: 'T0p_Secret_P@$$w0rd'
      roles: [ super ]
    sampleuser:
      password: '123456'
      roles: [ writers_space_reader ]
      privileges:
      - permissions: [ read, write ]
        spaces: [ books ]
  roles:
    writers_space_reader:
      privileges:
      - permissions: [ read ]
        spaces: [ writers ]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'

# Load sample data
app:
  file: 'myapp.lua'
