# grant privileges
sampleuser:
  password: '123456'
  roles: [ writers_space_reader ]
privileges:
- permissions: [read, write]
  spaces: [books]

# revoke a privilege:
sampleuser:
  password: '123456'
  roles: [ writers_space_reader ]
  privileges:
  - permissions: [read] # !! write permission revoked !!
    spaces: [books]
