# empty permissions array:
sampleuser:
  password: '123456'
  roles: [ writers_space_reader ]
privileges:
- permissions: [] # !! read permission revoked !!
  spaces: [books]

# empty privileges array:
sampleuser:
  password: '123456'
  roles: [ writers_space_reader ]
  privileges: [] # !! no privileges at all !!
