# grant privileges
    sampleuser:
      password: '123456'
      roles: [ writers_space_reader ]
      privileges:
      - permissions: [ read, write ]
        spaces: [ books ]

# take away a privilege:
    sampleuser:
      password: '123456'
      roles: [ writers_space_reader ]
      privileges:
      - permissions: [ read ]
        spaces: [ books ]

# take away all previously granted privileges:
    sampleuser:
      password: '123456'
      roles: [ writers_space_reader ]
      privileges: []
#      - permissions: [ read ]
#        spaces: [ books ]
