config:
  etcd:
    endpoints:
      - http://localhost:2379
    prefix: /example
    username: testuser
    password: foobar
    ssl:
      ca_file: ca.crt
    http:
      request:
        timeout: 3