credentials:
  users:
    admin:
      password: 'topsecret'
      roles: [ super ]

security:
  auth_type: 'pap-sha256'

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
                params:
                  transport: 'ssl'
                  ssl_cert_file: 'certs/server.crt'
                  ssl_key_file: 'certs/server.key'

app:
  file: 'myapp.lua'
