@startuml

skinparam {
    HyperlinkColor #0077FF
    FontColor #313131
    BorderColor #313131
    BackgroundColor transparent
}

json "**IPROTO_PREPARE**" as prepare_request {
    "Size": "MP_UINT",
    "Header": {
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_REQUEST_TYPE]]": "IPROTO_PREPARE",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_SYNC]]": "MP_UINT"
    },
    "Body": {
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_SQL_TEXT]]": "MP_STR"
    }
}

@enduml
