@startuml

skinparam {
    HyperlinkColor #0077FF
    FontColor #313131
    BorderColor #313131
    BackgroundColor transparent
}

json "**IPROTO_SUBSCRIBE**" as subscribe_request {
    "Size": "MP_UINT",
    "Header": {
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_REQUEST_TYPE]]": "IPROTO_SUBSCRIBE",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_SYNC]]": "MP_UINT"
    },
    "Body": {
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_INSTANCE_UUID]]": "MP_STR",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_CLUSTER_UUID]]": "MP_STR",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_INSTANCE_NAME]]": "MP_STR",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_REPLICASET_NAME]]": "MP_STR",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_VCLOCK]]": "MP_MAP",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_SERVER_VERSION]]": "MP_UINT",
      "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_REPLICA_ANON]]": "MP_BOOL",
      "(Optional) [[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys IPROTO_ID_FILTER]]": "MP_ARRAY"
    }
}

@enduml
