@startuml

skinparam {
    HyperlinkColor #0077FF
    FontColor #313131
    BorderColor #313131
    BackgroundColor transparent
}

json "**IPROTO_BALLOT body**" as ballot {
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_IS_RO_CFG]]": "MP_BOOL",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_VCLOCK]]": "MP_MAP",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_GC_VCLOCK]]": "MP_MAP",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_IS_RO]]": "MP_BOOL",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_IS_ANON]]": "MP_BOOL",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_IS_BOOTED]]": "MP_BOOL",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_CAN_LEAD]]": "MP_BOOL",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_BOOTSTRAP_LEADER_UUID]]": "MP_STR",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_REGISTERED_REPLICA_UUIDS]]": "MP_ARRAY",
    "[[https://tarantool.io/en/doc/latest/reference/internals/iproto/keys/#general-replication IPROTO_BALLOT_INSTANCE_NAME]]": "MP_STR"
}

@enduml
