credentials:
  users:
    admin:
      password: 'topsecret'
      roles: [ super ]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: 'unix/:./var/run/{{ instance_name }}/tarantool.iproto'
