credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]

iproto:
  advertise:
    peer: replicator@

replication:
  failover: election

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen: 127.0.0.1:3301
          instance002:
            iproto:
              listen: 127.0.0.1:3302
          instance003:
            iproto:
              listen: 127.0.0.1:3303

# Load sample data
app:
  file: 'data.lua'