@startuml

skinparam {
    HyperlinkColor #0077FF
    FontColor #313131
    BorderColor #313131
    BackgroundColor transparent
}

map "**Packet**" as Packet {
    size => MP_UINT
    header => MP_MAP
    body => MP_MAP
}

@enduml
