@startuml

skinparam map {
    HyperlinkColor #0077FF
    FontColor #313131
    BorderColor #313131
    BackgroundColor transparent
}

json "**Example of IPROTO_OK usage**" as ok_example {
    "Size": "MP_UINT",
    "Header": {
      "IPROTO_REQUEST_TYPE": "IPROTO_OK",
      "IPROTO_SYNC": "MP_UINT",
      "IPROTO_SCHEMA_VERSION": "MP_UINT"
    },
    "Body": {
      "IPROTO_DATA": "MP_OBJECT"
    }
}

@enduml
