name: Deploy

on:
  pull_request_target:
  workflow_dispatch:
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    container: tarantool/doc-builder:v1
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      S3_ENDPOINT_URL: ${{secrets.S3_ENDPOINT_URL}}
      S3_UPLOAD_PATH: ${{secrets.S3_UPLOAD_PATH}}
      TARANTOOL_UPDATE_KEY: ${{secrets.TARANTOOL_UPDATE_KEY}}
      TARANTOOL_UPDATE_URL: ${{secrets.TARANTOOL_DEV_UPDATE_URL}}
    steps:
      - uses: actions/checkout@v2
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release
      - run: cmake .
      - run: make pull-modules
      - run: make build-modules
      - run: make json
#      - run: make json-ru
      - uses: nelonoel/branch-name@v1.0.1
      - run: bash upload_output.sh
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://tarantool-develop.herokuapp.com/doc/{{$BRANCH}}
