name: Destroy-deployments

on:
  pull_request:
    types:
      - closed
jobs:
  destroy-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set branch name from source branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - run: |
          curl -X DELETE -d '{"update_key":"${{secrets.TARANTOOL_UPDATE_KEY}}"}' -H "Content-Type: application/json" ${{secrets.TARANTOOL_DEVELOP_UPDATE_URL}}${{env.BRANCH_NAME}}/

      - name: Remove dev server deployment at branch-${{env.BRANCH_NAME}}
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: deactivate-env
          token: ${{secrets.GITHUB_TOKEN}}
          env: "branch-${{env.BRANCH_NAME}}"

      - name: Remove translation deployment at translate-${{env.BRANCH_NAME}}
        uses: bobheadxi/deployments@v1.3.0
        id: translation
        with:
          step: deactivate-env
          token: ${{secrets.GITHUB_TOKEN}}
          env: "translation-${{env.BRANCH_NAME}}"
