name: Destroy-deployment-manually

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        description: 'Enter the name of GitHub deployment to remove'
        required: True
jobs:
  destroy-deployment-manually:
    runs-on: ubuntu-latest
    steps:
      - name: Update inputs
        run: |
          echo "DEPLOYMENT_NAME=${{github.event.inputs.deployment_name}}" >> $GITHUB_ENV
          echo "workaround until actions/runner#655 is fixed"

      - name: Remove dev server deployment at ${{env.DEPLOYMENT_NAME}}
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: "${{ secrets.TARANTOOLBOT_TOKEN }}"
          environment: ${{ env.DEPLOYMENT_NAME }}
#          onlyRemoveDeployments: true

      - run: |
          curl -X DELETE -d '{"update_key":"${{secrets.TARANTOOL_UPDATE_KEY}}"}' -H "Content-Type: application/json" ${{secrets.TARANTOOL_DEV_UPDATE_URL}}${{env.DEPLOYMENT_NAME}}/
