name: Destroy-deployment

on:
  pull_request:
    types:
      - closed
jobs:
  destroy-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -X DELETE -d '{"update_key":"${{secrets.TARANTOOL_UPDATE_KEY}}"}' -H "Content-Type: application/json" ${{secrets.TARANTOOL_DEV_UPDATE_URL}}${GITHUB_HEAD_REF##*/}/

      - name: Remove dev server deployment
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: deactivate-env
          token: ${{secrets.GITHUB_TOKEN}}
          env: "branch-${GITHUB_HEAD_REF##*/}"
