name: Update translations from Crowdin

on:
  workflow_dispatch:
  push:

jobs:
  pull-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull Po-files from crowdin
      uses: crowdin/github-action@1.0.21
      with:
        upload_sources: false
        upload_translations: false

        download_translations: true

        localization_branch_name: l10n_crowdin_action
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'New Crowdin pull request with translations'
        pull_request_labels: 'translation'
        pull_request_base_branch_name: latest

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
