name: Pull translations

on:
  workflow_dispatch:
    branches:
      - '!latest'

jobs:
  pull-translations:
    runs-on: ubuntu-latest
    container: tarantool/doc-builder:fat-1

    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.TARANTOOLBOT_TOKEN }}"

      - name: Set branch name from source branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update pot files
        run: |
          cmake .
          make update-pot

      - name: Pull translations from Crowdin
        uses: crowdin/github-action@1.0.21
        with:
          upload_sources: false
          upload_translations: false
          push_translations: false
          download_translations: true
          download_language: 'ru'
          crowdin_branch_name: "${{ env.BRANCH_NAME }}"
          debug_mode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Cleanup translation files
        run: make cleanup-po

      - name: Commit translation files
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Update translations"
          file_pattern: "*.po"
