name: Pull translations

on:
  workflow_dispatch:
    inputs:
      commit_po_for_unchanged_rst:
        description: 'Update translations for unchanged .rst'
        default: "false"
        required: True
    branches:
      - '!latest'

jobs:
  pull-translations:
    runs-on: ubuntu-latest
    container: tarantool/doc-builder:fat-4.1

    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.TARANTOOLBOT_TOKEN }}"
          fetch-depth: 0

      - name: Set branch name from source branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update pot files
        run: |
          cmake .
          make update-pot

      - name: Pull translations from Crowdin
        uses: crowdin/github-action@1.0.21
        with:
          upload_sources: false
          upload_translations: false
          push_translations: false
          download_translations: true
          download_language: 'ru'
          crowdin_branch_name: "${{ env.BRANCH_NAME }}"
          debug_mode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Cleanup translation files
        run: make cleanup-po

      - name: Set $CHANGED_POS for changed .rst files only
        shell: bash
        run: |
          set -x
          . list_changed_po.sh
          if [ -z "${CHANGED_POS}" ]; then exit 1; fi
          echo "CHANGED_POS=${CHANGED_POS}" >> $GITHUB_ENV
        if: ${{github.event.inputs.commit_po_for_unchanged_rst == 'false'}}

      - name: Set $CHANGED_POS for all .rst files
        run: echo "CHANGED_POS=*.po" >> $GITHUB_ENV
        if: ${{github.event.inputs.commit_po_for_unchanged_rst != 'false'}}

      - name: Commit translation files
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "Update translations"
          file_pattern: "${{ env.CHANGED_POS }}"
