name: Push POTs
on:
  push:
    branches:
      - '3.0'
      - 'lastochka42/update-po'
permissions:
  contents: write
jobs:
  generate-pot:
    runs-on: ubuntu-latest
    container: tarantool/doc-builder:fat-4.3
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Portable Object Templates
        run: |
         cmake .
         make update-po  

      - name: Commit generated pots
        run: |
          git config --global --add safe.directory /__w/doc/doc
          git config --global user.name 'TarantoolBot'
          git config --global user.email 'tarantoolbot@mail.ru'

          if [[ $(git status) =~ .*"nothing to commit".* ]]; then
            echo "status=nothing-to-commit"
            exit 0
          fi

          git add locale/
          git commit -m "updated locale"
          git push origin lastochka42/update-po

